# Generated by Django 2.0.2 on 2018-02-13 18:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20180213_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 13, 18, 29, 20, 59263, tzinfo=utc)),
        ),
    ]
