# Generated by Django 2.0.5 on 2018-05-26 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20180521_2024'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image_one',
            field=models.ImageField(blank=True, default='image.png', upload_to=''),
        ),
        migrations.AddField(
            model_name='post',
            name='image_three',
            field=models.ImageField(blank=True, default='image3.png', upload_to=''),
        ),
        migrations.AddField(
            model_name='post',
            name='image_two',
            field=models.ImageField(blank=True, default='image2.png', upload_to=''),
        ),
    ]
