# Generated by Django 2.0.5 on 2018-05-26 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20180521_2024'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.FileField(default='', upload_to='static/images/'),
        ),
    ]
