# Generated by Django 2.0.5 on 2018-05-31 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20180526_1702'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='text_three',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='post',
            name='text_two',
            field=models.TextField(default='N/A'),
        ),
    ]
